source /home/rr568/NPT/non-parametric-transformers/scripts/init_env_sklearn.sh

# For imputation dataset
# Default XGBoost
python run.py --data_set imputation --model_class sklearn-baselines --sklearn_model XGBoost --data_path /share/kuleshov/richras/npt/data/xgboost_x00 --data_force_reload True --exp_descr xgboost_imputation --num_win 0 --data_Kmer False --subWin_size 100 --exp_n_runs 1
# Default KNN
python run.py --data_set imputation --model_class sklearn-baselines --sklearn_model KNN --data_path /share/kuleshov/richras/npt/data/knn_x00 --data_force_reload True --exp_descr knn_imputation --exp_num_total_steps 60 --num_win 0 --Kmer_win_size 5 --data_Kmer True --subWin_size 100 --exp_n_runs 1
# Default GradientBoosting
python run.py --data_set imputation --model_class sklearn-baselines --sklearn_model GradientBoosting --data_path /share/kuleshov/richras/npt/data/gb_x00 --data_force_reload True --exp_descr gb_imputation --num_win 0 --subWin_size 100 --exp_n_runs 1 --project GradientBoosting
# Default MLP
python run.py --data_set imputation --model_class sklearn-baselines --sklearn_model MLP --data_path /share/kuleshov/richras/npt/data/mlp_x00 --data_force_reload True --exp_descr mlp_imputation --exp_num_total_steps 60 --num_win 0 --Kmer_win_size 5 --data_Kmer True --subWin_size 100


#For UCI datasets
#Breast Cancer Base_NPT
python run.py --data_set breast-cancer --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc True --model_num_heads 8 --model_stacking_depth 8 --exp_lr 5e-4 --exp_scheduler flat_and_anneal --exp_num_total_steps 2000 --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 32 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key breast_cancer__dim_hidden_32__bs_-1__feature_mask --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2 --data_path /share/kuleshov/richras/npt/data/breast_cancer_npt --exp_descr breast_cancer_BaseNPT --project Breast_Cancer
#Perceiver F
python run.py --data_set breast-cancer --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc True --model_num_heads 8 --model_stacking_depth 8 --exp_lr 5e-4 --exp_scheduler flat_and_anneal --exp_num_total_steps 2000 --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 32 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key breast_cancer__dim_hidden_32__bs_-1__feature_mask --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2 --data_path /share/kuleshov/richras/npt/data/breast_cancer_npt --exp_descr breast_cancer_SPIN --project Breast_Cancer --SPIN True --num_inds_I 10 --num_inds_F 10 --startAttBlock ABA
#Breast Cancer Perceiver E
python run.py --data_set breast-cancer --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc True --model_num_heads 8 --model_stacking_depth 8 --exp_lr 5e-4 --exp_scheduler flat_and_anneal --exp_num_total_steps 2000 --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 32 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key breast_cancer__dim_hidden_32__bs_-1__feature_mask --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2 --data_path /share/kuleshov/richras/npt/data/breast_cancer_npt --exp_descr breast_cancer_SPIN --project Breast_Cancer --perceiver_E True --num_inds_I 10 --num_inds_F 10 --enableEncoder True --data_force_reload True

#Higgs Base_NPT

#Income SPIN
#  batch size 2048, train for 2 000 000 steps, use no feature masking (and
# correspondingly fix the tradeoff parameter λ = 0), and use ptarget = 0.15.
python run.py --data_set income --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size 2048 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0, val=0, test=0)" --exp_tradeoff 0 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key concrete__bs_2048__feature_mask__label_mask_50 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2 --data_path /share/kuleshov/richras/npt/data/spin_income --exp_descr SPIN_income --data_force_reload True --project Income --SPIN True --num_inds_I 10 --num_inds_F 10 --startAttBlock ABA 

python run.py --data_set income --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size 2048 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0, val=0, test=0)" --exp_tradeoff 0 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key concrete__bs_2048__feature_mask__label_mask_50 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2 --data_path /share/kuleshov/richras/npt/data/spin_income --exp_descr SPIN_income_set_Transf --data_force_reload True --project Income --num_inds_I 10 --num_inds_F 10  --set_transformer True

# On Poker Hand, we use
# batch size 4096, train for 200 000 steps, use ptarget = 0.5, and stratify by class (i.e., compose training
# datapoints in each minibatch proportionally to the empirical label distribution of the training set to
# account for significant class imbalance).
python run.py --data_set 'poker-hand' --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size 4096 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 0 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key concrete__bs_2048__feature_mask__label_mask_50 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2 --data_path /share/kuleshov/richras/npt/data/poker_hand --exp_descr poker_hand_SPIN --data_force_reload True --project Poker_Hand --SPIN True --num_inds_I 10 --num_inds_F 10 --startAttBlock ABA 

python run.py --data_set 'poker-hand' --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size 4096 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 0 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key concrete__bs_2048__feature_mask__label_mask_50 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2 --data_path /share/kuleshov/richras/npt/data/poker_hand --exp_descr poker_hand_set_Transf --data_force_reload True --project Poker_Hand --num_inds_I 10 --num_inds_F 10  --set_transformer True


# On Forest Cover, we use batch size 1800, train for 800 000
# steps, use a polynomial decay learning rate scheduler with warmup over the first 1% of steps, use
# base learning rate 0.005, ptarget = 0.5, and class balancing as above.

python run.py --data_set 'forest-cover' --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 5e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size 1800 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0, val=0, test=0)" --exp_tradeoff 0 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key concrete__bs_2048__feature_mask__label_mask_50 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2 --data_path /share/kuleshov/richras/npt/data/spin_income --exp_descr SPIN_FC --data_force_reload True --project ForrestCover --SPIN True --num_inds_I 10 --num_inds_F 10 --startAttBlock ABA 

python run.py --data_set 'forest-cover' --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 5e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size 1800 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0, val=0, test=0)" --exp_tradeoff 0 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key concrete__bs_2048__feature_mask__label_mask_50 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2 --data_path /share/kuleshov/richras/npt/data/spin_income --exp_descr FC_set_Transf --data_force_reload True --project ForrestCover --num_inds_I 10 --num_inds_F 10 --set_transformer True


#Kicks Base_NPT

#Concrete Base_NPT

#Yacht Base_NPT

#Boston Housing Base_NPT
# Default
python run.py --data_set boston-housing --data_loader_nprocs=4 --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 20000 --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.15, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key boston__ablation__bs_-1__feature_mask__label_mask --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2 --data_path /share/kuleshov/richras/npt/data/boston_npt --exp_descr boston_BaseNPT_label_mask_0.15 --project Boston_Housing
# No Label Masking
python run.py --data_set boston-housing --data_loader_nprocs=4 --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 20000 --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key boston__ablation__bs_-1__feature_mask --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2 --data_path /share/kuleshov/richras/npt/data/boston_npt --exp_descr boston_BaseNPT_no_label_mask --project Boston_Housing
# BERT Label Aug to 0.5
python run.py --data_set boston-housing --data_loader_nprocs=4 --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 20000 --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key boston__ablation__bs_-1__feature_mask__label_mask_0.5 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2 --data_path /share/kuleshov/richras/npt/data/boston_npt --exp_descr boston_BaseNPT_label_mask_0.5 --project Boston_Housing
# Perceiver E
# Default
python run.py --data_set boston-housing --data_loader_nprocs=4 --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 20000 --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.15, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key boston__ablation__bs_-1__feature_mask__label_mask --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2 --data_path /share/kuleshov/richras/npt/data/boston_npt --exp_descr boston_Perceiver_E_label_mask_0.15 --project Boston_Housing --data_force_reload True --perceiver_E True --num_inds_I 10 --num_inds_F 10 --enableEncoder True

#Yacht Base_NPT
## Yacht
# Default
python run.py --data_set yacht --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key yacht__bs_-1__feature_mask --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2 --data_path /share/kuleshov/richras/npt/data/yacht_npt --exp_descr yacht_BaseNPT_no_label_mask --project Yacht --data_force_reload True
# Label Mask 0.10
python run.py --data_set yacht --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 20000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.1, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key yacht__bs_-1__feature_mask__label_mask_10 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2 --data_path /share/kuleshov/richras/npt/data/yacht_npt --exp_descr yacht_BaseNPT_label_mask_0.1 --project Yacht --data_force_reload True
# Perceiver
# Default
python run.py --data_set yacht --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key yacht__bs_-1__feature_mask --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2 --data_path /share/kuleshov/richras/npt/data/yacht_npt --exp_descr yacht_SPIN_no_label_mask --project Yacht --data_force_reload True --SPIN True --num_inds_I 10 --num_inds_F 5 --startAttBlock ABA
# Label Mask 0.10
python run.py --data_set yacht --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 20000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.1, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key yacht__bs_-1__feature_mask__label_mask_10 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2 --data_path /share/kuleshov/richras/npt/data/yacht_npt --exp_descr yacht_SPIN_label_mask_0.1 --project Yacht --data_force_reload True --SPIN True --num_inds_I 10 --num_inds_F 5 --startAttBlock ABA
# Perceiver E
# Default
python run.py --data_set yacht --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key yacht__bs_-1__feature_mask --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2 --data_path /share/kuleshov/richras/npt/data/yacht_npt --exp_descr yacht_Perceiver_E_no_label_mask --project Yacht --data_force_reload True --perceiver_E True --num_inds_I 10 --num_inds_F 5 --enableEncoder True


#Concrete Base_NPT
# Default
python run.py --data_set concrete --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key concrete__bs_-1__feature_mask --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2 --data_path /share/kuleshov/richras/npt/data/concrete_npt --exp_descr concrete_BaseNPT_no_label_mask --project Concrete --data_force_reload True
# Label Mask 0.50
python run.py --data_set concrete --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key concrete__bs_-1__feature_mask__label_mask_50 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2 --data_path /share/kuleshov/richras/npt/data/concrete_npt --exp_descr concrete_BaseNPT_label_mask_0.5 --project Concrete --data_force_reload True

# Default Perceiver
python run.py --data_set concrete --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key concrete__bs_-1__feature_mask_SPIN --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2 --data_path /share/kuleshov/richras/npt/data/concrete_npt --exp_descr concrete_BaseNPT_no_label_mask --project Concrete --data_force_reload True --SPIN True --num_inds_I 10 --num_inds_F 5 --startAttBlock ABA
python run.py --data_set concrete --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key concrete__bs_-1__feature_mask_SPIN --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2 --data_path /share/kuleshov/richras/npt/data/concrete_npt --exp_descr concrete_BaseNPT_no_label_mask_f_6 --project Concrete --data_force_reload True --SPIN True --num_inds_I 10 --num_inds_F 6 --startAttBlock ABA
# Label Mask 0.50
python run.py --data_set concrete --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key concrete__bs_-1__feature_mask__label_mask_50_SPIN --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2 --data_path /share/kuleshov/richras/npt/data/concrete_npt --exp_descr concrete_BaseNPT_label_mask_0.5 --project Concrete --data_force_reload True --SPIN True --num_inds_I 10 --num_inds_F 5 --startAttBlock ABA
#XABA only 
python run.py --data_set concrete --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key concrete__bs_-1__feature_mask_SPIN --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2 --data_path /share/kuleshov/richras/npt/data/concrete_npt --exp_descr concrete_Perceiver_D_no_label_mask --project Concrete --data_force_reload True --perceiver_E True --num_inds_I 10 --num_inds_F 5 --enableEncoder True

## Kick
python run.py --data_set kick --data_loader_nprocs=4 --exp_eval_every_n 5 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.7 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc True --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 250000  --exp_gradient_clipping 1 --exp_batch_size 4096 --model_dim_hidden 64 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key kick__bs_4096__feature_mask__label_mask --exp_descr Kick_BaseNPT --project Kick --data_force_reload True
# perceiver F
python run.py --data_set kick --data_loader_nprocs=4 --exp_eval_every_n 5 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.7 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc True --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 250000  --exp_gradient_clipping 1 --exp_batch_size 4096 --model_dim_hidden 64 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key kick__bs_4096__feature_mask__label_mask --SPIN True --num_inds_I 10 --num_inds_F 10 --startAttBlock ABA --exp_descr Kick_SPIN --project Kick --data_force_reload True
# perceiver E
python run.py --data_set kick --data_loader_nprocs=4 --exp_eval_every_n 5 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.7 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc True --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 250000  --exp_gradient_clipping 1 --exp_batch_size 4096 --model_dim_hidden 64 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key kick__bs_4096__feature_mask__label_mask --perceiver_E True --num_inds_I 10 --num_inds_F 10 --exp_descr Kick_Perceiver_E --project Kick --data_force_reload True --enableEncoder True

#Genomics Imputation
#Base NPT - diff seeds 42,52,62
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_0_embed_64_depth_6_heads_4_bs_-1_np_seed_42 --num_win 0 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT --exp_num_total_steps 15000 --np_seed 42 --project BaseNPT
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_1_embed_64_depth_6_heads_4_bs_-1_np_seed_42 --num_win 1 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT --exp_num_total_steps 15000 --np_seed 42 --project BaseNPT
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_2_embed_64_depth_6_heads_4_bs_-1_np_seed_42 --num_win 2 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT --exp_num_total_steps 15000 --np_seed 42 --project BaseNPT
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_3_embed_64_depth_6_heads_4_bs_-1_np_seed_42 --num_win 3 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT --exp_num_total_steps 15000 --np_seed 42 --project BaseNPT
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_4_embed_64_depth_6_heads_4_bs_-1_np_seed_42 --num_win 4 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT --exp_num_total_steps 15000 --np_seed 42 --project BaseNPT

--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_0_embed_64_depth_6_heads_4_bs_-1_np_seed_52 --num_win 0 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT --exp_num_total_steps 15000 --np_seed 52 --project BaseNPT
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_1_embed_64_depth_6_heads_4_bs_-1_np_seed_52 --num_win 1 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT --exp_num_total_steps 15000 --np_seed 52 --project BaseNPT
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_2_embed_64_depth_6_heads_4_bs_-1_np_seed_52 --num_win 2 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT --exp_num_total_steps 15000 --np_seed 52 --project BaseNPT
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_3_embed_64_depth_6_heads_4_bs_-1_np_seed_52 --num_win 3 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT --exp_num_total_steps 15000 --np_seed 52 --project BaseNPT
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_4_embed_64_depth_6_heads_4_bs_-1_np_seed_52 --num_win 4 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT --exp_num_total_steps 15000 --np_seed 52 --project BaseNPT


--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_0_embed_64_depth_6_heads_4_bs_-1_np_seed_62 --num_win 0 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT --exp_num_total_steps 15000 --np_seed 62 --project BaseNPT
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_1_embed_64_depth_6_heads_4_bs_-1_np_seed_62 --num_win 1 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT --exp_num_total_steps 15000 --np_seed 62 --project BaseNPT
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_2_embed_64_depth_6_heads_4_bs_-1_np_seed_62 --num_win 2 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT --exp_num_total_steps 15000 --np_seed 62 --project BaseNPT
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_3_embed_64_depth_6_heads_4_bs_-1_np_seed_62 --num_win 3 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT --exp_num_total_steps 15000 --np_seed 62 --project BaseNPT
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_4_embed_64_depth_6_heads_4_bs_-1_np_seed_62 --num_win 4 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT --exp_num_total_steps 15000 --np_seed 62 --project BaseNPT


#Base NPT with label mask 0.5 - diff seeds 42,52,62,72,82

--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_0_embed_64_depth_6_heads_4_bs_-1_np_seed_62_lb_0.5 --num_win 0 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT_lb_0.5 --exp_num_total_steps 30000 --np_seed 62 --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --project BaseNPT
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_1_embed_64_depth_6_heads_4_bs_-1_np_seed_62_lb_0.5 --num_win 1 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT_lb_0.5 --exp_num_total_steps 30000 --np_seed 62 --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --project BaseNPT
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_2_embed_64_depth_6_heads_4_bs_-1_np_seed_62_lb_0.5 --num_win 2 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT_lb_0.5 --exp_num_total_steps 30000 --np_seed 62 --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --project BaseNPT
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_3_embed_64_depth_6_heads_4_bs_-1_np_seed_62_lb_0.5 --num_win 3 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT_lb_0.5 --exp_num_total_steps 30000 --np_seed 62 --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --project BaseNPT
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_4_embed_64_depth_6_heads_4_bs_-1_np_seed_62_lb_0.5 --num_win 4 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT_lb_0.5 --exp_num_total_steps 30000 --np_seed 62 --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --project BaseNPT

--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_0_embed_64_depth_6_heads_4_bs_-1_np_seed_52_lb_0.5 --num_win 0 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT_lb_0.5 --exp_num_total_steps 30000 --np_seed 52 --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --project BaseNPT
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_1_embed_64_depth_6_heads_4_bs_-1_np_seed_52_lb_0.5 --num_win 1 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT_lb_0.5 --exp_num_total_steps 30000 --np_seed 52 --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --project BaseNPT
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_2_embed_64_depth_6_heads_4_bs_-1_np_seed_52_lb_0.5 --num_win 2 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT_lb_0.5 --exp_num_total_steps 30000 --np_seed 52 --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --project BaseNPT
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_3_embed_64_depth_6_heads_4_bs_-1_np_seed_52_lb_0.5 --num_win 3 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT_lb_0.5 --exp_num_total_steps 30000 --np_seed 52 --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --project BaseNPT
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_4_embed_64_depth_6_heads_4_bs_-1_np_seed_52_lb_0.5 --num_win 4 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT_lb_0.5 --exp_num_total_steps 30000 --np_seed 52 --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --project BaseNPT

--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_0_embed_64_depth_6_heads_4_bs_-1_np_seed_42_lb_0.5 --num_win 0 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT_lb_0.5 --exp_num_total_steps 30000 --np_seed 42 --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --project BaseNPT
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_1_embed_64_depth_6_heads_4_bs_-1_np_seed_42_lb_0.5 --num_win 1 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT_lb_0.5 --exp_num_total_steps 30000 --np_seed 42 --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --project BaseNPT
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_2_embed_64_depth_6_heads_4_bs_-1_np_seed_42_lb_0.5 --num_win 2 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT_lb_0.5 --exp_num_total_steps 30000 --np_seed 42 --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --project BaseNPT
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_3_embed_64_depth_6_heads_4_bs_-1_np_seed_42_lb_0.5 --num_win 3 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT_lb_0.5 --exp_num_total_steps 30000 --np_seed 42 --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --project BaseNPT
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr BaseNPT_it_4_embed_64_depth_6_heads_4_bs_-1_np_seed_42_lb_0.5 --num_win 4 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key BaseNPT_lb_0.5 --exp_num_total_steps 30000 --np_seed 42 --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --project BaseNPT

#Parametric transformer
#inductive mode (train only train, val only val, test only test), only ABA, diff seeds 42,52,62
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 8 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr ParametricTransf_it_0_embed_64_depth_4_heads_4_bs_-1_np_seed_62 --num_win 0 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key ParametricTransf --exp_num_total_steps 30000 --np_seed 62 --model_is_semi_supervised False --onlyABA True --project ParametricTransf
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 8 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr ParametricTransf_it_1_embed_64_depth_4_heads_4_bs_-1_np_seed_62 --num_win 1 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key ParametricTransf --exp_num_total_steps 30000 --np_seed 62 --model_is_semi_supervised False --onlyABA True --project ParametricTransf
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 8 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr ParametricTransf_it_2_embed_64_depth_4_heads_4_bs_-1_np_seed_62 --num_win 2 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key ParametricTransf --exp_num_total_steps 30000 --np_seed 62 --model_is_semi_supervised False --onlyABA True --project ParametricTransf
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 8 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr ParametricTransf_it_3_embed_64_depth_4_heads_4_bs_-1_np_seed_62 --num_win 3 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key ParametricTransf --exp_num_total_steps 30000 --np_seed 62 --model_is_semi_supervised False --onlyABA True --project ParametricTransf
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 8 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr ParametricTransf_it_4_embed_64_depth_4_heads_4_bs_-1_np_seed_62 --num_win 4 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key ParametricTransf --exp_num_total_steps 30000 --np_seed 62 --model_is_semi_supervised False --onlyABA True --project ParametricTransf

--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 8 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr ParametricTransf_it_0_embed_64_depth_4_heads_4_bs_-1_np_seed_52 --num_win 0 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key ParametricTransf --exp_num_total_steps 30000 --np_seed 52 --model_is_semi_supervised False --onlyABA True --project ParametricTransf
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 8 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr ParametricTransf_it_1_embed_64_depth_4_heads_4_bs_-1_np_seed_52 --num_win 1 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key ParametricTransf --exp_num_total_steps 30000 --np_seed 52 --model_is_semi_supervised False --onlyABA True --project ParametricTransf
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 8 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr ParametricTransf_it_2_embed_64_depth_4_heads_4_bs_-1_np_seed_52 --num_win 2 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key ParametricTransf --exp_num_total_steps 30000 --np_seed 52 --model_is_semi_supervised False --onlyABA True --project ParametricTransf
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 8 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr ParametricTransf_it_3_embed_64_depth_4_heads_4_bs_-1_np_seed_52 --num_win 3 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key ParametricTransf --exp_num_total_steps 30000 --np_seed 52 --model_is_semi_supervised False --onlyABA True --project ParametricTransf
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 8 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr ParametricTransf_it_4_embed_64_depth_4_heads_4_bs_-1_np_seed_52 --num_win 4 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key ParametricTransf --exp_num_total_steps 30000 --np_seed 52 --model_is_semi_supervised False --onlyABA True --project ParametricTransf

--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 8 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr ParametricTransf_it_0_embed_64_depth_4_heads_4_bs_-1_np_seed_42 --num_win 0 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key ParametricTransf --exp_num_total_steps 30000 --np_seed 42 --model_is_semi_supervised False --onlyABA True --project ParametricTransf
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 8 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr ParametricTransf_it_1_embed_64_depth_4_heads_4_bs_-1_np_seed_42 --num_win 1 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key ParametricTransf --exp_num_total_steps 30000 --np_seed 42 --model_is_semi_supervised False --onlyABA True --project ParametricTransf
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 8 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr ParametricTransf_it_2_embed_64_depth_4_heads_4_bs_-1_np_seed_42 --num_win 2 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key ParametricTransf --exp_num_total_steps 30000 --np_seed 42 --model_is_semi_supervised False --onlyABA True --project ParametricTransf
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 8 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr ParametricTransf_it_3_embed_64_depth_4_heads_4_bs_-1_np_seed_42 --num_win 3 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key ParametricTransf --exp_num_total_steps 30000 --np_seed 42 --model_is_semi_supervised False --onlyABA True --project ParametricTransf
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 8 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr ParametricTransf_it_4_embed_64_depth_4_heads_4_bs_-1_np_seed_42 --num_win 4 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer False --perceiver_E False --viz_att_maps False --model_checkpoint_key ParametricTransf --exp_num_total_steps 30000 --np_seed 42 --model_is_semi_supervised False --onlyABA True --project ParametricTransf

#Set transformer
# diff seeds 42,52,62
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_0_embed_64_depth_6_heads_4_bs_-1_np_seed_62 --num_win 0 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf --exp_num_total_steps 15000 --np_seed 62  --project SetTransf
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_1_embed_64_depth_6_heads_4_bs_-1_np_seed_62 --num_win 1 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf --exp_num_total_steps 15000 --np_seed 62  --project SetTransf
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_2_embed_64_depth_6_heads_4_bs_-1_np_seed_62 --num_win 2 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf --exp_num_total_steps 15000 --np_seed 62  --project SetTransf
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_3_embed_64_depth_6_heads_4_bs_-1_np_seed_62 --num_win 3 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf --exp_num_total_steps 15000 --np_seed 62  --project SetTransf
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_4_embed_64_depth_6_heads_4_bs_-1_np_seed_62 --num_win 4 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf --exp_num_total_steps 15000 --np_seed 62  --project SetTransf

--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_0_embed_64_depth_6_heads_4_bs_-1_np_seed_52 --num_win 0 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf --exp_num_total_steps 15000 --np_seed 52  --project SetTransf
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_1_embed_64_depth_6_heads_4_bs_-1_np_seed_52 --num_win 1 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf --exp_num_total_steps 15000 --np_seed 52  --project SetTransf
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_2_embed_64_depth_6_heads_4_bs_-1_np_seed_52 --num_win 2 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf --exp_num_total_steps 15000 --np_seed 52  --project SetTransf
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_3_embed_64_depth_6_heads_4_bs_-1_np_seed_52 --num_win 3 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf --exp_num_total_steps 15000 --np_seed 52  --project SetTransf
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_4_embed_64_depth_6_heads_4_bs_-1_np_seed_52 --num_win 4 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf --exp_num_total_steps 15000 --np_seed 52  --project SetTransf

--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_0_embed_64_depth_6_heads_4_bs_-1_np_seed_42 --num_win 0 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf --exp_num_total_steps 15000 --np_seed 42  --project SetTransf
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_1_embed_64_depth_6_heads_4_bs_-1_np_seed_42 --num_win 1 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf --exp_num_total_steps 15000 --np_seed 42  --project SetTransf
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_2_embed_64_depth_6_heads_4_bs_-1_np_seed_42 --num_win 2 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf --exp_num_total_steps 15000 --np_seed 42  --project SetTransf
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_3_embed_64_depth_6_heads_4_bs_-1_np_seed_42 --num_win 3 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf --exp_num_total_steps 15000 --np_seed 42  --project SetTransf
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_4_embed_64_depth_6_heads_4_bs_-1_np_seed_42 --num_win 4 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf --exp_num_total_steps 15000 --np_seed 42  --project SetTransf

# diff seeds 42,52,62, label mask 0.5
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_0_embed_64_depth_6_heads_4_bs_-1_np_seed_62_lb_0.5 --num_win 0 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf_lb_0.5 --exp_num_total_steps 30000 --np_seed 62  --project SetTransf --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)"
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_1_embed_64_depth_6_heads_4_bs_-1_np_seed_62_lb_0.5 --num_win 1 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf_lb_0.5 --exp_num_total_steps 30000 --np_seed 62  --project SetTransf --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)"
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_2_embed_64_depth_6_heads_4_bs_-1_np_seed_62_lb_0.5 --num_win 2 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf_lb_0.5 --exp_num_total_steps 30000 --np_seed 62  --project SetTransf --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)"
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_3_embed_64_depth_6_heads_4_bs_-1_np_seed_62_lb_0.5 --num_win 3 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf_lb_0.5 --exp_num_total_steps 30000 --np_seed 62  --project SetTransf --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)"
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_4_embed_64_depth_6_heads_4_bs_-1_np_seed_62_lb_0.5 --num_win 4 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf_lb_0.5 --exp_num_total_steps 30000 --np_seed 62  --project SetTransf --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)"

--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_0_embed_64_depth_6_heads_4_bs_-1_np_seed_52_lb_0.5 --num_win 0 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf_lb_0.5 --exp_num_total_steps 30000 --np_seed 52  --project SetTransf --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)"
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_1_embed_64_depth_6_heads_4_bs_-1_np_seed_52_lb_0.5 --num_win 1 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf_lb_0.5 --exp_num_total_steps 30000 --np_seed 52  --project SetTransf --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)"
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_2_embed_64_depth_6_heads_4_bs_-1_np_seed_52_lb_0.5 --num_win 2 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf_lb_0.5 --exp_num_total_steps 30000 --np_seed 52  --project SetTransf --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)"
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_3_embed_64_depth_6_heads_4_bs_-1_np_seed_52_lb_0.5 --num_win 3 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf_lb_0.5 --exp_num_total_steps 30000 --np_seed 52  --project SetTransf --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)"
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_4_embed_64_depth_6_heads_4_bs_-1_np_seed_52_lb_0.5 --num_win 4 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf_lb_0.5 --exp_num_total_steps 30000 --np_seed 52  --project SetTransf --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)"

--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_0_embed_64_depth_6_heads_4_bs_-1_np_seed_42_lb_0.5 --num_win 0 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf_lb_0.5 --exp_num_total_steps 30000 --np_seed 42  --project SetTransf --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)"
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_1_embed_64_depth_6_heads_4_bs_-1_np_seed_42_lb_0.5 --num_win 1 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf_lb_0.5 --exp_num_total_steps 30000 --np_seed 42  --project SetTransf --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)"
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_2_embed_64_depth_6_heads_4_bs_-1_np_seed_42_lb_0.5 --num_win 2 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf_lb_0.5 --exp_num_total_steps 30000 --np_seed 42  --project SetTransf --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)"
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_3_embed_64_depth_6_heads_4_bs_-1_np_seed_42_lb_0.5 --num_win 3 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf_lb_0.5 --exp_num_total_steps 30000 --np_seed 42  --project SetTransf --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)"
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 6 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SetTransf_it_4_embed_64_depth_6_heads_4_bs_-1_np_seed_42_lb_0.5 --num_win 4 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --set_transformer True --perceiver_E False --viz_att_maps False --model_checkpoint_key SetTransf_lb_0.5 --exp_num_total_steps 30000 --np_seed 42  --project SetTransf --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)"

# Protein Dataset
--data_set protein --data_loader_nprocs=4 --exp_eval_every_n 5 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.7 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 16 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 400000 --exp_gradient_clipping 1 --exp_batch_size 2048 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.15, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key protein__ablation__bs_2048__feature_mask__label_mask__heads_16 --project protein --data_path /share/kuleshov/richras/npt/data/protein_npt --exp_descr protein_NPT
--data_set protein --data_loader_nprocs=4 --exp_eval_every_n 5 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.7 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 16 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 400000 --exp_gradient_clipping 1 --exp_batch_size 2048 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.15, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key protein__ablation__bs_2048__feature_mask__label_mask__heads_16 --project protein --data_path /share/kuleshov/richras/npt/data/protein_spin --exp_descr protein_SPIN --data_force_reload True --SPIN True --num_inds_I 10 --num_inds_F 10 --startAttBlock ABA

# Multiple windows experiment
#window_size=100, num_windows=10
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 4 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr new_masking_spin_num_10_win_embed_64_depth_4_bs_-1_lb_0.85_enEncoder_no_random_bert --num_win 10 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 100 --model_hidden_dropout_prob 0.4 --viz_att_maps False --model_checkpoint_key SPIN_mw --exp_num_total_steps 100000 --model_label_bert_mask_prob "dict(train=0.7, val=0.0, test=0.0)" --np_seed 42 --SPIN True --enableEncoder True --startAttBlock ABA --project Multiple_Win --multiple_win True --exp_eval_every_n 1 --exp_optimizer_warmup_proportion 0.5 --exp_tradeoff 0.1 --model_bert_mask_percentage 1.0

#window_size=200, num_windows=10
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 4 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr new_masking_spin_num_10_win_size_200 --num_win 10 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 200 --model_hidden_dropout_prob 0.4 --viz_att_maps False --model_checkpoint_key SPIN_mw --exp_num_total_steps 100000 --model_label_bert_mask_prob "dict(train=0.15, val=0.0, test=0.0)" --np_seed 42 --SPIN True --enableEncoder True --startAttBlock ABA --project Multiple_Win --multiple_win True --exp_eval_every_n 1 --exp_optimizer_warmup_proportion 0.5 --exp_tradeoff 0.1 --model_bert_mask_percentage 1.0 --chunk_mask True

#window_size=400, num_windows=10
--data_set imputation --model_dim_hidden 64 --model_num_heads 4 --model_stacking_depth 4 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr new_masking_spin_num_10_win_size_400 --num_win 10 --Kmer_win_size 5 --data_Kmer True --exp_batch_size -1 --subWin_size 400 --model_hidden_dropout_prob 0.4 --viz_att_maps False --model_checkpoint_key SPIN_mw --exp_num_total_steps 100000 --model_label_bert_mask_prob "dict(train=0.15, val=0.0, test=0.0)" --np_seed 42 --SPIN True --enableEncoder True --startAttBlock ABA --project Multiple_Win --multiple_win True --exp_eval_every_n 1 --exp_optimizer_warmup_proportion 0.5 --exp_tradeoff 0.1 --model_bert_mask_percentage 1.0 --chunk_mask True

#synthetic expt
--data_set synthetic_att --model_dim_hidden 32 --model_num_heads 1 --model_stacking_depth 1 --data_path /share/kuleshov/richras/npt/data/testing_x00 --data_force_reload True --exp_descr SPIN_synthetic_ncols_4_p_0.1_2_cent_mixed_labels_rev_0.1_0.1_I_2 --exp_batch_size -1 --model_hidden_dropout_prob 0.4 --viz_att_maps False --model_checkpoint_key perceiver_F_mw --exp_num_total_steps 15000 --np_seed 42 --perceiver_D True --project Synthetic --startAttBlock ABD --exp_eval_every_n 1 --model_bert_augmentation True --model_augmentation_bert_mask_prob "dict(train=0, val=0, test=0)" --dataSynthetic_query 600 --dataSynthetic_n_rows 6000 --dataSynthetic_n_cols 4 --allow_even_only_stacking_depth False --bernoulliNoise 0.1 --ABLA False --num_inds_I 2